services:
  jericho:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/violetrimberg/cephalon-jericho:latest
    restart: unless-stopped
    volumes:
      - ./state.json:/app/state.json
      - ./.env:/app/.env # Define your environment variables here
